apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-api-test
  annotations:
    github.com/project-slug: barecode/backstage-api-test
spec:
  type: other
  lifecycle: unknown
  owner: guests
