apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backstage-api-test
  description: Simple Hello World API to test registration of an API with backstage.io
  annotations:
    github.com/project-slug: barecode/backstage-api-test
  links:
    - url: https://api-manager.us-east-a.apiconnect.automation.ibm.com/manager/acme-coffee-roasters/
      title: ACME Coffee Roasters: API Management Portal
      icon: dashboard
      type: admin-dashboard
spec:
  type: openapi
  lifecycle: production
  owner: guests
  system: examples
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Backstage API Test
    servers:
      - url: http://localhost:8000/
        description: Localhost node.js app
    paths:
      /hello_world:
        get:
          summary: Responds with Hello World
          responses:
            '200':
              description: |-
                200 response
              content:
                text/plain:
                  schema:
                    type: string
                    example: Hello world

