apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backstage-api-test
  description: Simple Hello World API to test registration of an API with backstage.io
  annotations:
    github.com/project-slug: barecode/backstage-api-test
spec:
  type: other
  lifecycle: unknown
  owner: guests
