apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backstage-api-test
  description: Simple Hello World API to test registration of an API with backstage.io
  annotations:
    github.com/project-slug: barecode/backstage-api-test
spec:
  type: openapi
  lifecycle: production
  owner: guests
  spec.definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Backstage API Test
      license:
        name: MIT
    servers:
      - url: http://localhost:8000/
    paths:
      /hello_world
        get:
          summary: Responds with Hello World

